### ISSUE TITLE
Thoughts on SQLMapper extending to support NoSQL - ODM - Object Document Mapper

### ISSUE THREAD

**Issue by nagkumar** [sqlcomponents/sqlcomponents#50] opened 2022-10-15 04:20 UTC
As analytics are quite popular these days, use of NoSQL has also grown, as they also have SQL, is it worth extending the sqlmapper solution to support NoSQL ODM DBs?

**Comment by sathishk** [comment] 2024-01-09 04:54
By Design, This project expects well defined schema and standard sql compliance. Closing this issue

**Closed by sathishk** 2024-01-09 04:54 UTC
Labels: enhancement
