### ISSUE TITLE
Plugablitity - NoSQLs

### ISSUE THREAD

**Issue by nagkumar** [sqlcomponents/sqlcomponents#66] opened 2023-07-26 02:33 UTC
Decide if we can support NoSQLs too.. ideally, we should be able to..

In order to support millions of customers, the product should be customizable for different no databases which exist currently and which may come up in the future.

However, we can define a few popular NoSQLs as a priority and get to fix the pluggability issues in the current architecture

**Comment by sathishk** [comment] 2024-01-09 08:44
By Design we need SQL Support. So closing this

**Closed by sathishk** 2024-01-09 08:44 UTC
Labels: refactoring
